name: Static Analysis
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  python-coding-style:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend

      - run: uv run ruff check .

      - run: uv run ruff format --check .

  frontend-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend

      - run: npm run lint

  frontend-format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend

      - run: npm run check-format

  python-type-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend

      - run: uv run pyright .

  yaml-format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend

      - run: uv run yamlfix --check $(find . -type f -name '*.yml' -o -name '*.yaml' | grep -v -E '\.venv/|node_modules/')
