name: Static Analysis
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  backend-format:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend

      - name: Check backend formatting
        run: uv run ruff check .

      - name: Check backend code style
        run: uv run ruff format --check .

  frontend-lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend

      - name: Check frontend linting
        run: npm run frontend:lint

  frontend-format:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend

      - name: Check frontend formatting
        run: npm run frontend:check:format

  backend-types:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend

      - name: Check backend types
        run: uv run pyright .

  yaml-format:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend

      - name: Check YAML formatting
        run: uv run yamlfix --check $(find . -type f -name '*.yml' -o -name '*.yaml' | grep -v -E '\.venv/|node_modules/')
